### ISSUE TITLE
Font style and control placement and menu allows clipping.

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3487]
<img width="295" alt="Screen Shot 2020-11-02 at 2 17 03 PM" src="https://user-images.githubusercontent.com/1056412/97931804-5316dc00-1d23-11eb-984b-db1bbacd3740.png">

Problem indicated with red arrow. Seen on hulk/dev 11-02-20. Move control where it belongs, and set menu to align right. #3296, should be integrated with new menu API, get @deeptailor involved.

**Comment by charlesh88** [comment]
Fixes pushed to `fix-font-menus-3487` branch. @deeptailor Over to you for new menu API changes.

### Testing Notes
1. Create or edit a Display Layout. Also add an object that uses font size and styling, like a plot, table or text drawing object.
1. Select the layout's child object. In the Styles tab, verify that the toggle grid button is right-aligned (purple arrow) and that the font style control is to the left (orange arrow), right after the font size control. Click to display the menu and verify that each menu option doesn't have left margin, as shown below.

<img width="424" alt="Screen Shot 2020-11-02 at 4 20 34 PM" src="https://user-images.githubusercontent.com/1056412/97933444-a0954800-1d27-11eb-94b4-02d7c0f60b19.png">

3. Click the font style control and verify that its menu also doesn't have left margin: 

<img width="426" alt="Screen Shot 2020-11-02 at 4 20 42 PM" src="https://user-images.githubusercontent.com/1056412/97933445-a12dde80-1d27-11eb-8a93-ff1912258135.png">

**Comment by charlesh88** [comment]
Still a problem, seen running VISTA locally in `R4.6-Release-Candidates` branch today:

<img width="287" alt="Screen Shot 2020-12-17 at 6 26 32 PM" src="https://user-images.githubusercontent.com/1056412/102567346-372e8600-4096-11eb-92c1-a4bc2634c192.png">

**Comment by akhenry** [comment]
Verified Fixed in testathon

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 01/07/2021

**Comment by shefalijoshi** [comment]
Verified

**Comment by davetsay** [comment]
partially verified.

in vista still see issue. most likely the deployed version

Version Information
Version: 1.5.0-SNAPSHOT
Build Date: Thu Dec 17 2020 11:26:45 GMT-0800 (Pacific Standard Time)
Revision: c8fe0fb7563d8c9cc179f01261fdd90b18428b21
Branch: HEAD
