### ISSUE TITLE
Plans folder gives false sense of editability

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3741]
## Overview
Deployment specific. VIPER Plans folder does not prevent editing actions such as creating and/or renaming objects. Will get persistence errors.

## Expected Behavior
Folder shouldn't be selectable for create destination. Name should not be editable.

## Steps to Reproduce
create
1. Create any object from the Create Menu
2. Select VIPER Plans Folder to save into
3. Save

rename
1. Select VIPER Plans Folder
2. Rename a plan via the browse bar

**Comment by charlesh88** [comment]
Verified fixed Testathon 12-13-21.

**Comment by nikhilmandlik** [comment]
Can context click on Viper Plans and edit properties (and also for its child Plans objects)

**Comment by unlikelyzero** [comment]
Re-opening based on 

> Can context click on Viper Plans and edit properties (and also for its child Plans objects)

**Comment by jvigliotta** [comment]
This was fixed, but then overwritten in new form stuff, new PR should reintroduce those checks.

**Comment by unlikelyzero** [comment]
Retest

**Comment by nikhilmandlik** [comment]
Unable to create plane view. 😭

**Comment by nikhilmandlik** [comment]
not fixed :(

<img width="493" alt="Screen Shot 2022-01-06 at 2 43 16 PM" src="https://user-images.githubusercontent.com/1292612/148462741-15e21527-2242-4a56-93fc-a996f8987567.png">
<img width="431" alt="Screen Shot 2022-01-06 at 2 43 26 PM" src="https://user-images.githubusercontent.com/1292612/148462747-8d39e8f2-84fb-45e2-9f2f-dddd2a474213.png">

**Comment by akhenry** [comment]
I have also observed this with other non-editable folder types, so the fix should not be limited to plan folders.

**Comment by unlikelyzero** [comment]
Still an issue

**Comment by akhenry** [comment]
Suspect that this is an instance of this broader problem - https://github.com/nasa/openmct/issues/4323

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 03/14/2021

**Comment by nikhilmandlik** [comment]
Verified Fixed.
