### ISSUE TITLE
[New Edit Mode] Example Imagery allowed to drop into Panel Fixed Position view

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#424]
I was able to drop an Example Imagery element into a panel, but the result was weird, see screenshot. 

Recommended fix: given that FPV in Panels and Panels themselves are going away, disable Imagery from being included as an object type in FPV in a Panel. Note that this is very low priority, unless we plan to include Example Imagery in our VISTA Beta.

![screen shot 2015-12-11 at 4 25 04 pm](https://cloud.githubusercontent.com/assets/1056412/11758777/448e9e10-a024-11e5-949c-f6123a1d29ad.png)

**Comment by charlesh88** [comment]
Another shot, result of dragging Imagery onto a Panel. Note that "Imagery" added to the plot.

![screen shot 2015-12-11 at 4 31 12 pm](https://cloud.githubusercontent.com/assets/1056412/11758804/b626be22-a024-11e5-899d-67d738ad53ac.png)

**Comment by akhenry** [comment]
Yeah, had noticed this as well. It seems the existing policy allows it. I'll see what I can do to disable it for imagery.

**Comment by charlesh88** [comment]
Cool, only fix if easy.

**Comment by akhenry** [comment]
The panel allows composition with Imagery telemetry because [in its definition](https://github.com/nasa/openmctweb/blob/master/platform/features/layout/bundle.json#L241) it explicitly allows composition by any object with telemetry capability. This applies not just to fixed layout panels, but also plot panels.

Fixed layout panels are going away, so I'm disinclined to fix it there. It does need to be corrected for plots though, and limiting the scope of the fix to plots only actually makes it a little simpler I think. The answer might be to provide more nuanced composition rules via a policy that checks whether the object being added to the composition has a telemetry capability AND the data type of the telemetry is numerical. If it's non-numerical, then it can't be plotted. @VWoeltjen does this sound like a reasonable approach?

**Comment by VWoeltjen** [comment]
Moving from Baxter to Bradbury (clearing out issues still assigned to the old sprint). I don't recall for certain where we landed on this during sprint planning, so it may belong in Clarke or backlog instead.

> Fixed layout panels are going away, so I'm disinclined to fix it there. It does need to be corrected for plots though, and limiting the scope of the fix to plots only actually makes it a little simpler I think. The answer might be to provide more nuanced composition rules via a policy that checks whether the object being added to the composition has a telemetry capability AND the data type of the telemetry is numerical. If it's non-numerical, then it can't be plotted. @VWoeltjen does this sound like a reasonable approach?

There's a bit of a quirk where "plot" is a way of visualizing a set of telemetry elements. Showing the URL for images in a scrolling list seems reasonable in this case, so I don't think that disallowing non-numeric telemetry at composition time is the right answer here. (This would have the immediate consequence of breaking Fixed Position configurations that use string telemetry, for example.)

I think the lowest-impact change would be for the plot _view_ to filter out any non-numeric telemetry elements before displaying. Would probably want to provide the user with some way of knowing that there are points in the Telemetry Panel which are not being plotted and why (off the top of my head, I'd say grey them out in the legend area and show "This Telemetry Point cannot be plotted. Its telemetry values are not numeric.") @charlesh88 - what do you think?

**Comment by akhenry** [comment]
Yep, sorry, I was conflating two concepts here which are composability and viewability. Currently we have strategies for determining both, but they're not currently nuanced enough, for panels at least, to handle composition by objects with different telemetry types.

As a result of the sprint planning meeting for Bradbury I've created #454 to do some analysis of the broader issue here.

**Comment by akhenry** [comment]
Suggest we implement @VWoeltjen's suggestion https://github.com/nasa/openmctweb/issues/424#issuecomment-169436753 as part of NEM implementation. Plots should make a determination about whether they can plot the telemetry of each composed object (based on data type) and if it can't, then it should not show the values, but still show the label with some indication that it's 'disabled'.

**Comment by charlesh88** [comment]
Closing this, Panels should not have time spent on them.
